name: onnxruntime_builds
description: ONNX Runtime binaries.
version: 0.0.1
repository: https://github.com/NathanKolbas/onnxruntime_builds

environment:
  sdk: ^3.10.1

dependencies:
  hooks: ^1.0.0
  code_assets: ^1.0.0
  ed25519_edwards: ^0.3.1
  http: ^1.6.0
  github: ^9.25.0
  path: ^1.9.1
  logging: ^1.3.0
  hex: ^0.2.0
  yaml: ^3.1.3
  args: ^2.7.0
  collection: ^1.19.1
  version: ^3.0.2
  source_span: ^1.10.1
  convert: ^3.1.2
  crypto: ^3.0.7
  ffi: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

# TODO: Does this work for other packages that use this package?
hooks:
  user_defines:
    onnxruntime_builds:
      local_build: false
      precompiled_binaries:
        url_prefix: https://github.com/NathanKolbas/onnxruntime_builds/releases/download/precompiled_
        public_key: 831ae16527e53bac21703b45b9823d151e440ed8e8423403082c8d531cb0f38d
