on:
  push:
    branches:
      - main

name: Precompile Binaries

jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      # Windows, at the time of writing, defaults to python 3.9 but ONNX Runtime needs at least 3.10
      - uses: actions/setup-python@v6
        if: matrix.os == 'windows-latest'
        with:
          python-version: 'pypy3.10'
      - name: Install GTK
        if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'ubuntu-24.04-arm')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev

      # Modified step for macOS due to older cmake needed
      - name: Precompile (macOS)
        if: matrix.os == 'macOS-latest'
        run: >
          dart run ./tool/build.dart precompile-binaries -v
          --repository NathanKolbas/onnxruntime_builds
          --cmake_extra_defines "CMAKE_POLICY_VERSION_MINIMUM=3.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}

      - name: Precompile
        if: (matrix.os == 'ubuntu-24.04-arm') || (matrix.os == 'windows-latest')
        run: dart run ./tool/build.dart precompile-binaries -v --repository NathanKolbas/onnxruntime_builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}

      # For the x86_64 Linux runner we compile both Linux and Android
      - name: Precompile (with Android)
        if: (matrix.os == 'ubuntu-latest')
        run: dart run ./tool/build.dart precompile-binaries -v --repository NathanKolbas/onnxruntime_builds --android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
