on:
  push:
    branches:
      - main

name: Precompile Binaries

jobs:
  Precompile:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install GTK
        if: (matrix.os == 'ubuntu-latest') || (matrix.os == 'ubuntu-24.04-arm')
        run: sudo apt-get update && sudo apt-get install libgtk-3-dev
      - name: Precompile
        if: (matrix.os == 'ubuntu-24.04-arm') || (matrix.os == 'macOS-latest') || (matrix.os == 'windows-latest')
        run: dart run ./tool/build.dart precompile-binaries -v --repository NathanKolbas/onnxruntime_builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Precompile (with Android)
        if: (matrix.os == 'ubuntu-latest')
        run: dart run ./tool/build.dart precompile-binaries -v --repository NathanKolbas/onnxruntime_builds --android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}
